# Generated by Django 5.0.6 on 2024-07-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libro_direccion_alter_libro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='horarios',
            field=models.TextField(null=True, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='libro',
            name='telefono',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
