# Generated by Django 5.0.6 on 2024-07-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_libro_horarios_libro_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='horarios',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='telefono',
        ),
    ]
