# Generated by Django 5.0.6 on 2024-07-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_titulo_libro_nombre_remove_libro_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='contadorComentarios',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='contadorVisitaEvaluador',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='contadorVisitaInvitado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='promedioCalificaciones',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='telefono'),
        ),
    ]
