# Generated by Django 5.0.6 on 2024-07-25 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_libro_contadorcomentarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('claveUsuario', models.CharField(max_length=100)),
                ('nombrePersona', models.CharField(max_length=100)),
                ('apellidoPersona', models.CharField(max_length=100)),
                ('perfilCreado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('claveUsuario', models.CharField(max_length=100)),
                ('nombrePersona', models.CharField(max_length=100)),
                ('apellidoPersona', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.empresa'),
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentarioEvaluador', models.TextField()),
                ('puntuacionServicio', models.IntegerField()),
                ('puntuacionProducto', models.IntegerField()),
                ('perfilEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.evaluadores')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='id_evaluadoresEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.evaluadores'),
        ),
        migrations.CreateModel(
            name='GaleriaEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagenGaleria1', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('imagenGaleria2', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('imagenGaleria3', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('imagenGaleria4', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('perfilEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='id_galeriaEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='libreria.galeriaempresa'),
        ),
        migrations.CreateModel(
            name='HorariosEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionHorario', models.TextField()),
                ('horarioApertura', models.TimeField()),
                ('horarioCierre', models.TimeField()),
                ('perfilEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productosEmpresa', models.TextField()),
                ('perfilEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.CreateModel(
            name='RedesSocialesEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correoEmpresa', models.EmailField(max_length=254)),
                ('paginaWebEmpresa', models.URLField(blank=True, null=True)),
                ('InstagramEmpresa', models.URLField(blank=True, null=True)),
                ('FacebookEmpresa', models.URLField(blank=True, null=True)),
                ('WhatsappEmpresa', models.CharField(blank=True, max_length=15, null=True)),
                ('perfilEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviciosEmpresa', models.TextField()),
                ('perfilEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='id_serviciosEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='libreria.serviciosempresa'),
        ),
    ]
