# Generated by Django 5.0.6 on 2024-07-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_libro_id_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadores',
            name='perfilCreado',
            field=models.BooleanField(default=False),
        ),
    ]
