# Generated by Django 5.0.6 on 2024-07-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_evaluadores_perfilcreado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='claveUsuario',
        ),
        migrations.RemoveField(
            model_name='evaluadores',
            name='claveUsuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='password',
            field=models.CharField(default='temporarypassword', max_length=128),
        ),
        migrations.AddField(
            model_name='evaluadores',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='evaluadores',
            name='password',
            field=models.CharField(default=1234, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombreUsuario',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='perfilCreado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluadores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluadores',
            name='nombreUsuario',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluadores',
            name='perfilCreado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
