# Generated by Django 5.0.6 on 2024-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_remove_empresa_claveusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluadores',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluadores',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
