# Generated by Django 5.0.6 on 2024-07-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_empresa_is_active_empresa_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciones',
            name='evaluador',
        ),
    ]
