# Generated by Django 5.0.6 on 2024-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_remove_evaluaciones_evaluador'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('evaluador', 'Evaluador')], default='empresa', max_length=10),
        ),
    ]
