# Generated by Django 5.0.6 on 2024-07-28 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_evaluaciones_usuarioevaluador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='libro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='Teléfono'),
        ),
    ]
