# Generated by Django 5.0.6 on 2024-07-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_remove_libro_id_empresa_libro_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
