# Generated by Django 5.0.6 on 2024-11-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_evaluaciones_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciones',
            name='puntuacionProducto',
        ),
    ]
